// Mockdata: Clientes cadastrados a partir de conversas e reservas
window.MOCK_CLIENTS = [
  {
    id: "client-001",
    name: "Helena Borges",
    initials: "HB",
    phone: "+55 11 9 8842-1109",
    lastContact: "Hoje, 11:42",
    conversationId: "c-001",
    preferences: ["Vegetariana", "Mesa próxima à janela", "Cliente recorrente"],
    notes: "Costuma reservar no almoço e prefere atendimento discreto. Valoriza mesas com boa luz natural.",
    reservationHistory: [
      {
        id: "rh-001-a",
        date: "Hoje",
        time: "12:00",
        party: 2,
        status: "confirmada",
        table: "Mesa 4",
        area: "Salão Principal",
        notes: "Prefere mesa próxima à janela.",
      },
      {
        id: "rh-001-b",
        date: "24 out",
        time: "20:15",
        party: 2,
        status: "confirmada",
        table: "Mesa 5",
        area: "Salão Principal",
        notes: "Pediu carta de vinhos na chegada.",
      },
      {
        id: "rh-001-c",
        date: "02 out",
        time: "12:30",
        party: 3,
        status: "confirmada",
        table: "Mesa 7",
        area: "Salão Principal",
        notes: "Avisou restrição vegetariana com antecedência.",
      },
    ],
  },
  {
    id: "client-002",
    name: "Rafael Tavares",
    initials: "RT",
    phone: "+55 11 9 9412-7732",
    lastContact: "Hoje, 11:38",
    conversationId: "c-002",
    preferences: ["Área externa", "Com criança", "Intolerância: Lactose", "Com pet"],
    notes: "Perguntou se poderia levar cachorro pequeno. Uma criança do grupo tem intolerância à lactose.",
    reservationHistory: [
      {
        id: "rh-002-a",
        date: "Hoje",
        time: "12:30",
        party: 4,
        status: "aguardando",
        table: "Mesa 11",
        area: "Área Externa",
        notes: "Cliente perguntou se pode trazer cachorro pequeno.",
      },
      {
        id: "rh-002-b",
        date: "18 out",
        time: "13:00",
        party: 3,
        status: "confirmada",
        table: "Mesa 10",
        area: "Área Externa",
        notes: "Preferiu área externa por estar com criança.",
      },
    ],
  },
  {
    id: "client-003",
    name: "Camila Sodré",
    initials: "CS",
    phone: "+55 11 9 7301-4422",
    lastContact: "Hoje, 10:22",
    conversationId: "c-003",
    preferences: ["Intolerância: Glúten", "Comemoração", "Grupo grande"],
    notes: "Avisar cozinha sobre restrição a glúten. Em comemorações, costuma trazer bolo.",
    reservationHistory: [
      {
        id: "rh-003-a",
        date: "Hoje",
        time: "13:00",
        party: 6,
        status: "ativa",
        table: "Mesa 8",
        area: "Salão Principal",
        notes: "Aniversário. Trouxe bolo, cobrar rolha de bolo.",
      },
      {
        id: "rh-003-b",
        date: "11 out",
        time: "20:45",
        party: 5,
        status: "confirmada",
        table: "Mesa 8",
        area: "Salão Principal",
        notes: "Solicitou sobremesa sem glúten.",
      },
    ],
  },
  {
    id: "client-004",
    name: "Theo Mascarenhas",
    initials: "TM",
    phone: "+55 11 9 9120-7745",
    lastContact: "Hoje, 09:42",
    conversationId: "c-004",
    preferences: ["Primeira visita", "Mezanino"],
    notes: "Reserva feita pelo WhatsApp. Ainda sem preferências recorrentes registradas.",
    reservationHistory: [
      {
        id: "rh-004-a",
        date: "Hoje",
        time: "13:15",
        party: 2,
        status: "confirmada",
        table: "Mesa 2",
        area: "Mezanino",
        notes: "Primeira visita. Reserva feita pelo WhatsApp às 09:42.",
      },
    ],
  },
  {
    id: "client-005",
    name: "Marina Queiroga",
    initials: "MQ",
    phone: "+55 11 9 9885-3310",
    lastContact: "Hoje, 09:11",
    conversationId: "c-005",
    preferences: ["Com criança", "Cadeirão", "Salão Principal"],
    notes: "Solicita cadeirão quando vem com a filha. Prefere mesas com circulação fácil.",
    reservationHistory: [
      {
        id: "rh-005-a",
        date: "Hoje",
        time: "13:45",
        party: 3,
        status: "aguardando",
        table: "Mesa 9",
        area: "Salão Principal",
        notes: "Cliente pediu cadeirão para criança de 2 anos.",
      },
      {
        id: "rh-005-b",
        date: "21 set",
        time: "12:15",
        party: 3,
        status: "confirmada",
        table: "Mesa 6",
        area: "Salão Principal",
        notes: "Pediu cadeira infantil e prato extra.",
      },
    ],
  },
  {
    id: "client-006",
    name: "Otávio Pellegrini",
    initials: "OP",
    phone: "+55 11 9 9612-0098",
    lastContact: "Ontem",
    conversationId: "c-006",
    preferences: ["Sem porco", "Mesa silenciosa", "Reunião de negócios"],
    notes: "Geralmente vem com grupos maiores. Priorizar canto do salão e serviço mais reservado.",
    reservationHistory: [
      {
        id: "rh-006-a",
        date: "Hoje",
        time: "14:00",
        party: 8,
        status: "confirmada",
        table: "Mesa 14",
        area: "Salão Principal",
        notes: "Reunião de negócios. Pedir mesa silenciosa.",
      },
      {
        id: "rh-006-b",
        date: "05 out",
        time: "19:00",
        party: 7,
        status: "confirmada",
        table: "Mesa 13",
        area: "Salão Principal",
        notes: "Solicitou canto do salão.",
      },
    ],
  },
  {
    id: "client-007",
    name: "Beatriz Hollanda",
    initials: "BH",
    phone: "+55 11 9 9335-7711",
    lastContact: "Hoje, 08:55",
    conversationId: "c-007",
    preferences: ["Vegana", "Intolerância: Castanhas", "Atenção da equipe"],
    notes: "Conversa fora do roteiro sobre opções veganas. Confirmar contaminação cruzada com castanhas.",
    reservationHistory: [
      {
        id: "rh-007-a",
        date: "Hoje",
        time: "20:30",
        party: 4,
        status: "aguardando",
        table: "Mesa 10",
        area: "Salão Principal",
        notes: "Conversa fora do roteiro. Equipe deve responder.",
      },
      {
        id: "rh-007-b",
        date: "28 set",
        time: "20:00",
        party: 2,
        status: "confirmada",
        table: "Mesa 3",
        area: "Mezanino",
        notes: "Pediu menu vegano antes de chegar.",
      },
    ],
  },
  {
    id: "client-008",
    name: "Diego Albuquerque",
    initials: "DA",
    phone: "+55 11 9 9881-1042",
    lastContact: "Ontem",
    conversationId: "c-008",
    preferences: ["Área externa", "Grupo médio", "Sensível ao clima"],
    notes: "Cancelou reserva por chuva forte. Em dias instáveis, oferecer salão principal como alternativa.",
    reservationHistory: [
      {
        id: "rh-008-a",
        date: "Hoje",
        time: "20:00",
        party: 5,
        status: "cancelada",
        table: "Mesa 12",
        area: "Área Externa",
        notes: "Cancelado pelo cliente às 16:12 — chuva forte.",
      },
      {
        id: "rh-008-b",
        date: "13 out",
        time: "21:15",
        party: 4,
        status: "confirmada",
        table: "Mesa 12",
        area: "Área Externa",
        notes: "Preferiu área externa.",
      },
    ],
  },
  {
    id: "client-009",
    name: "Vinícius Saldanha",
    initials: "VS",
    phone: "+55 11 9 9087-3322",
    lastContact: "Ontem",
    conversationId: "c-009",
    preferences: ["Bar", "Balcão", "Vinho específico"],
    notes: "Prefere sentar no balcão do bar e costuma pedir vinho específico antes de chegar.",
    reservationHistory: [
      {
        id: "rh-009-a",
        date: "Hoje",
        time: "21:00",
        party: 2,
        status: "confirmada",
        table: "Mesa 1",
        area: "Bar",
        notes: "Prefere balcão do bar. Pediu vinho específico.",
      },
      {
        id: "rh-009-b",
        date: "19 set",
        time: "20:30",
        party: 2,
        status: "confirmada",
        table: "Mesa 1",
        area: "Bar",
        notes: "Pediu para reservar duas taças do mesmo rótulo.",
      },
    ],
  },
  {
    id: "client-010",
    name: "Luísa Cavalcanti",
    initials: "LC",
    phone: "+55 11 9 9712-2014",
    lastContact: "Ontem",
    conversationId: "c-010",
    preferences: ["Mezanino", "Sobremesa surpresa", "Comemoração"],
    notes: "Gosta de reservas no mezanino. Em datas especiais, pede sobremesa com vela.",
    reservationHistory: [
      {
        id: "rh-010-a",
        date: "Hoje",
        time: "19:30",
        party: 2,
        status: "confirmada",
        table: "Mesa 6",
        area: "Mezanino",
        notes: "Pedido de surpresa: trazer sobremesa com vela.",
      },
      {
        id: "rh-010-b",
        date: "07 out",
        time: "19:45",
        party: 2,
        status: "confirmada",
        table: "Mesa 6",
        area: "Mezanino",
        notes: "Aniversário de namoro.",
      },
    ],
  },
];
