// Mockdata: Conversas e mensagens
window.MOCK_CONVERSATIONS = [
  {
    id: "c-001",
    name: "Helena Borges",
    initials: "HB",
    preview: "Perfeito, obrigada! Vejo vocês amanhã.",
    time: "11:42",
    status: "confirmada",
    unread: 0,
    offScript: false,
    reservationId: "r-001",
    summary: { date: "Hoje", time: "12:00", party: 2, area: "Salão Principal", table: "Mesa 4" },
  },
  {
    id: "c-002",
    name: "Rafael Tavares",
    initials: "RT",
    preview: "Posso levar meu cachorro? Ele é pequeno.",
    time: "11:38",
    status: "aguardando",
    unread: 2,
    offScript: true,
    reservationId: "r-002",
    summary: { date: "Hoje", time: "12:30", party: 4, area: "Área Externa", table: "Mesa 11" },
  },
  {
    id: "c-003",
    name: "Camila Sodré",
    initials: "CS",
    preview: "IA: Reserva confirmada para 6 pessoas às 13:00.",
    time: "10:22",
    status: "ativa",
    unread: 0,
    offScript: false,
    reservationId: "r-003",
    summary: { date: "Hoje", time: "13:00", party: 6, area: "Salão Principal", table: "Mesa 8" },
  },
  {
    id: "c-004",
    name: "Theo Mascarenhas",
    initials: "TM",
    preview: "IA: Tudo certo, te esperamos!",
    time: "09:42",
    status: "confirmada",
    unread: 0,
    offScript: false,
    reservationId: "r-004",
    summary: { date: "Hoje", time: "13:15", party: 2, area: "Mezanino", table: "Mesa 2" },
  },
  {
    id: "c-005",
    name: "Marina Queiroga",
    initials: "MQ",
    preview: "Vocês têm cadeirão disponível?",
    time: "09:11",
    status: "aguardando",
    unread: 1,
    offScript: false,
    reservationId: "r-005",
    summary: { date: "Hoje", time: "13:45", party: 3, area: "Salão Principal", table: "Mesa 9" },
  },
  {
    id: "c-006",
    name: "Otávio Pellegrini",
    initials: "OP",
    preview: "IA: Perfeito, mesa para 8 reservada.",
    time: "Ontem",
    status: "confirmada",
    unread: 0,
    offScript: false,
    reservationId: "r-006",
    summary: { date: "Hoje", time: "14:00", party: 8, area: "Salão Principal", table: "Mesa 14" },
  },
  {
    id: "c-007",
    name: "Beatriz Hollanda",
    initials: "BH",
    preview: "Gostaria de saber se vocês têm opções veganas que",
    time: "08:55",
    status: "aguardando",
    unread: 3,
    offScript: true,
    reservationId: "r-009",
    summary: { date: "Hoje", time: "20:30", party: 4, area: "Salão Principal", table: "Mesa 10" },
  },
  {
    id: "c-008",
    name: "Diego Albuquerque",
    initials: "DA",
    preview: "Cliente: Vou precisar cancelar, está chovendo muito.",
    time: "Ontem",
    status: "cancelada",
    unread: 0,
    offScript: false,
    reservationId: "r-008",
    summary: { date: "Hoje", time: "20:00", party: 5, area: "Área Externa", table: "Mesa 12" },
  },
  {
    id: "c-009",
    name: "Vinícius Saldanha",
    initials: "VS",
    preview: "IA: Vinho reservado. Até mais tarde!",
    time: "Ontem",
    status: "confirmada",
    unread: 0,
    offScript: false,
    reservationId: "r-010",
    summary: { date: "Hoje", time: "21:00", party: 2, area: "Bar", table: "Mesa 1" },
  },
  {
    id: "c-010",
    name: "Luísa Cavalcanti",
    initials: "LC",
    preview: "IA: Sobremesa surpresa anotada.",
    time: "Ontem",
    status: "confirmada",
    unread: 0,
    offScript: false,
    reservationId: "r-007",
    summary: { date: "Hoje", time: "19:30", party: 2, area: "Mezanino", table: "Mesa 6" },
  },
];

// Mensagens da conversa selecionada (Rafael Tavares — fora do roteiro)
window.MOCK_MESSAGES = {
  "c-002": [
    { id: 1, from: "ai",     text: "Olá! Aqui é a recepcionista virtual do Mesa. Como posso ajudar?", time: "11:24" },
    { id: 2, from: "client", text: "Oi, queria reservar uma mesa para hoje, por volta das 12:30.", time: "11:25" },
    { id: 3, from: "ai",     text: "Perfeito. Para quantas pessoas?", time: "11:25" },
    { id: 4, from: "client", text: "4 pessoas, sendo uma criança.", time: "11:26" },
    { id: 5, from: "ai",     text: "Anotado. Qual o seu nome para a reserva?", time: "11:26" },
    { id: 6, from: "client", text: "Rafael Tavares.", time: "11:27" },
    { id: 7, from: "ai",     text: "Obrigada, Rafael. Alguma preferência de área? Temos salão principal e área externa.", time: "11:27" },
    { id: 8, from: "client", text: "Externa, por favor.", time: "11:28" },
    { id: 9, from: "ai",     text: "Anotado. Alguma restrição alimentar ou intolerância?", time: "11:28" },
    { id: 10, from: "client", text: "Lactose, na criança.", time: "11:29" },
    { id: 11, from: "ai",     text: "Certo. Reserva pré-confirmada para 4 pessoas às 12:30 na área externa, em nome de Rafael. Confirma?", time: "11:30" },
    { id: 12, from: "client", text: "Confirmo. Posso levar meu cachorro? Ele é pequeno.", time: "11:38" },
    { id: 13, from: "system", text: "Conversa fora do roteiro — aguardando equipe.", time: "11:38", offScript: true },
  ],
};
