// Mockdata: Reservas — fictícias, fáceis de remover
window.MOCK_RESERVATIONS = [
  {
    id: "r-001",
    time: "12:00",
    name: "Helena Borges",
    party: 2,
    status: "confirmada",
    table: "Mesa 4",
    area: "Salão Principal",
    notes: "Cliente recorrente. Prefere mesa próxima à janela.",
    diet: ["Vegetariana"],
    intolerances: [],
    children: false,
    pet: false,
    celebration: null,
    areaPref: "Janela",
    phone: "+55 11 9 8842-1109",
  },
  {
    id: "r-002",
    time: "12:30",
    name: "Rafael Tavares",
    party: 4,
    status: "aguardando",
    table: "Mesa 11",
    area: "Área Externa",
    notes: "Cliente perguntou se pode trazer cachorro pequeno.",
    diet: [],
    intolerances: ["Lactose"],
    children: true,
    pet: true,
    celebration: null,
    areaPref: "Externa",
    phone: "+55 11 9 9412-7732",
  },
  {
    id: "r-003",
    time: "13:00",
    name: "Camila Sodré",
    party: 6,
    status: "chegando",
    table: "Mesa 8",
    area: "Salão Principal",
    notes: "Aniversário. Trouxe bolo, cobrar rolha de bolo.",
    diet: [],
    intolerances: ["Glúten"],
    children: false,
    pet: false,
    celebration: "Aniversário de 32 anos",
    areaPref: "Centro do salão",
    phone: "+55 11 9 7301-4422",
  },
  {
    id: "r-004",
    time: "13:15",
    name: "Theo Mascarenhas",
    party: 2,
    status: "confirmada",
    table: "Mesa 2",
    area: "Mezanino",
    notes: "Primeira visita. Reserva feita pelo WhatsApp às 09:42.",
    diet: [],
    intolerances: [],
    children: false,
    pet: false,
    celebration: null,
    areaPref: null,
    phone: "+55 11 9 9120-7745",
  },
  {
    id: "r-005",
    time: "13:45",
    name: "Marina Queiroga",
    party: 3,
    status: "aguardando",
    table: "Mesa 9",
    area: "Salão Principal",
    notes: "Cliente pediu cadeirão para criança de 2 anos.",
    diet: [],
    intolerances: [],
    children: true,
    pet: false,
    celebration: null,
    areaPref: null,
    phone: "+55 11 9 9885-3310",
  },
  {
    id: "r-006",
    time: "14:00",
    name: "Otávio Pellegrini",
    party: 8,
    status: "confirmada",
    table: "Mesa 14",
    area: "Salão Principal",
    notes: "Reunião de negócios. Pedir mesa silenciosa.",
    diet: ["Sem porco"],
    intolerances: [],
    children: false,
    pet: false,
    celebration: null,
    areaPref: "Canto do salão",
    phone: "+55 11 9 9612-0098",
  },
  {
    id: "r-007",
    time: "19:30",
    name: "Luísa Cavalcanti",
    party: 2,
    status: "confirmada",
    table: "Mesa 6",
    area: "Mezanino",
    notes: "Pedido de surpresa: trazer sobremesa com vela.",
    diet: [],
    intolerances: [],
    children: false,
    pet: false,
    celebration: "Aniversário de namoro",
    areaPref: "Mezanino",
    phone: "+55 11 9 9712-2014",
  },
  {
    id: "r-008",
    time: "20:00",
    name: "Diego Albuquerque",
    party: 5,
    status: "cancelada",
    table: "Mesa 12",
    area: "Área Externa",
    notes: "Cancelado pelo cliente às 16:12 — chuva forte.",
    diet: [],
    intolerances: [],
    children: false,
    pet: false,
    celebration: null,
    areaPref: "Externa",
    phone: "+55 11 9 9881-1042",
  },
  {
    id: "r-009",
    time: "20:30",
    name: "Beatriz Hollanda",
    party: 4,
    status: "aguardando",
    table: "Mesa 10",
    area: "Salão Principal",
    notes: "Conversa fora do roteiro. Equipe deve responder.",
    diet: ["Vegana"],
    intolerances: ["Castanhas"],
    children: false,
    pet: false,
    celebration: null,
    areaPref: null,
    phone: "+55 11 9 9335-7711",
  },
  {
    id: "r-010",
    time: "21:00",
    name: "Vinícius Saldanha",
    party: 2,
    status: "confirmada",
    table: "Mesa 1",
    area: "Bar",
    notes: "Prefere balcão do bar. Pediu vinho específico.",
    diet: [],
    intolerances: [],
    children: false,
    pet: false,
    celebration: null,
    areaPref: "Bar",
    phone: "+55 11 9 9087-3322",
  },
];

// Dias do mês — para o seletor
window.MOCK_DAYS = (() => {
  const days = [];
  const today = 6; // dia 6 ativo
  for (let i = 1; i <= 14; i++) {
    days.push({
      day: i,
      weekday: ["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][(i-1) % 7],
      count: i === today ? 10 : i === 7 ? 14 : i === 8 ? 11 : i === 5 ? 8 : i === 4 ? 6 : i % 3 === 0 ? 4 : i % 2 === 0 ? 7 : 0,
      active: i === today,
    });
  }
  return days;
})();
