// Mockdata: Equipe
window.MOCK_TEAM = [
  {
    id: "t-001",
    name: "Mariana Bastos",
    role: "Gerente",
    phone: "+55 11 9 8810-2244",
    tables: "Todas",
    notifications: ["Nova reserva", "Reserva confirmada", "Cliente chegando", "Reserva cancelada"],
    advance: "1 hora antes",
    initials: "MB",
  },
  {
    id: "t-002",
    name: "Felipe Andrade",
    role: "Recepção",
    phone: "+55 11 9 8721-3398",
    tables: "Todas",
    notifications: ["Cliente chegando", "Reserva cancelada"],
    advance: "10 min antes",
    initials: "FA",
  },
  {
    id: "t-003",
    name: "Patrícia Nogueira",
    role: "Garçom",
    phone: "+55 11 9 8809-4471",
    tables: "Mesa 1, 2, 3, 4",
    notifications: ["Cliente chegando"],
    advance: "30 min antes",
    initials: "PN",
  },
  {
    id: "t-004",
    name: "Henrique Lobo",
    role: "Garçom",
    phone: "+55 11 9 8762-1190",
    tables: "Mesa 5, 6, 7, 8",
    notifications: ["Cliente chegando", "Nova reserva"],
    advance: "30 min antes",
    initials: "HL",
  },
  {
    id: "t-005",
    name: "Rodrigo Sá",
    role: "Cozinha",
    phone: "+55 11 9 8845-5520",
    tables: "—",
    notifications: ["Reserva confirmada"],
    advance: "1 hora antes",
    initials: "RS",
  },
  {
    id: "t-006",
    name: "Tatiana Vieira",
    role: "Bar",
    phone: "+55 11 9 8810-7782",
    tables: "Mesa 1 (bar)",
    notifications: ["Cliente chegando"],
    advance: "Na chegada",
    initials: "TV",
  },
];
